# Configuração central do projeto Sentinela Verde
from pathlib import Path
import os

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ID = os.getenv("EE_PROJECT", "estudos-dos-dados-tcc")

ANO_INICIO = 2017
ANO_FIM = 2026
MES_DIA_INICIO = "05-01"
MES_DIA_FIM = "08-01"

MAX_CLOUD_PERCENT = 20
ESCALA_S2 = 10
ESCALA_LST = 30
RAIO_ANALISE = 5000
RAIO_CONTROLE_INTERNO = 5000
RAIO_CONTROLE_EXTERNO = 10000

SEED = 42
PERCENTUAL_TREINO = 0.70
NUM_ARVORES = 100
PONTOS_POR_CLASSE = 1500

BANDAS_S2 = ["B2","B3","B4","B8","B11","B12"]
INDICES_SPECTRAIS = ["NDVI","NDWI","NDBI"]
BANDAS_ML = BANDAS_S2 + INDICES_SPECTRAIS

COLECAO_S2 = "COPERNICUS/S2_SR_HARMONIZED"
COLECAO_MAPBIOMAS = "projects/mapbiomas-public/assets/brazil/lulc/v1"
ANO_MAPBIOMAS = 2023

COLECAO_VIIRS = "NASA/VIIRS/002/VNP46A2"
BANDA_VIIRS = "Gap_Filled_DNB_BRDF_Corrected_NTL"

COLECAO_L8 = "LANDSAT/LC08/C02/T2_L2"
COLECAO_L9 = "LANDSAT/LC09/C02/T2_L2"

COLECAO_DYNAMIC_WORLD = "GOOGLE/DYNAMICWORLD/V1"
COLECAO_ERA5 = "ECMWF/ERA5_LAND/MONTHLY_AGGR"
COLECAO_GSW = "JRC/GSW1_4/GlobalSurfaceWater"
COLECAO_WORLDPOP = "WorldPop/GP/100m/pop"

ROOT_DATA = PROJECT_ROOT / "data"
RAW_DIR = ROOT_DATA / "raw"
PROCESSED_DIR = ROOT_DATA / "processed"
MODELS_DIR = ROOT_DATA / "models"
RESULTS_DIR = ROOT_DATA / "results"
EXTERNAL_DIR = ROOT_DATA / "external"

for _d in [RAW_DIR, PROCESSED_DIR, MODELS_DIR, RESULTS_DIR, EXTERNAL_DIR]:
    _d.mkdir(parents=True, exist_ok=True)

DATA_CENTERS = [
    {
        "facility_id": "DC_001",
        "facility_name": "Ascenty Sumaré 1",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Sumaré",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2017,
        "operational_year": 2017,
        "construction_end_year": null,
        "capacity_mw": 14.0,
        "it_load_mw": null,
        "facility_area_m2": 11000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/data-centers/localizacao/brasil/sao-paulo-interior/sumare/sumare-1/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_002",
        "facility_name": "Ascenty Sumaré 2",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Sumaré",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2019,
        "operational_year": 2019,
        "construction_end_year": null,
        "capacity_mw": 20.0,
        "it_load_mw": null,
        "facility_area_m2": 12000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/data-centers/localizacao/brasil/sao-paulo-interior/sumare/sumare-2/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_003",
        "facility_name": "Ascenty Hortolândia 2",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Hortolândia",
        "address": null,
        "latitude": -22.896022,
        "longitude": -47.179246,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2019,
        "operational_year": 2019,
        "construction_end_year": null,
        "capacity_mw": 7.0,
        "it_load_mw": null,
        "facility_area_m2": 3000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/blog/artigos/data-center-em-sao-paulo/",
        "coordinate_status": "Validada",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_004",
        "facility_name": "Ascenty Hortolândia 3",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Hortolândia",
        "address": null,
        "latitude": -22.896022,
        "longitude": -47.179246,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2019,
        "operational_year": 2019,
        "construction_end_year": null,
        "capacity_mw": 3.0,
        "it_load_mw": null,
        "facility_area_m2": 2000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/blog/artigos/data-center-em-sao-paulo/",
        "coordinate_status": "Validada",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_005",
        "facility_name": "Ascenty Paulínia 1",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Paulínia",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2019,
        "operational_year": 2019,
        "construction_end_year": null,
        "capacity_mw": 13.0,
        "it_load_mw": null,
        "facility_area_m2": 8000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/blog/artigos/data-center-em-sao-paulo/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_006",
        "facility_name": "Ascenty Vinhedo 1",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Vinhedo",
        "address": null,
        "latitude": -23.071035,
        "longitude": -47.011837,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": 2018,
        "opening_year": 2019,
        "operational_year": 2019,
        "construction_end_year": 2019,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/data-centers/localizacao/brasil/sao-paulo-interior/vinhedo/",
        "coordinate_status": "Validada",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_007",
        "facility_name": "Ascenty Jundiaí 2",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Jundiaí",
        "address": null,
        "latitude": -23.191744,
        "longitude": -46.974604,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2019,
        "operational_year": 2019,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/",
        "coordinate_status": "Validada",
        "data_quality": "Média"
    },
    {
        "facility_id": "DC_008",
        "facility_name": "Ascenty Vinhedo 2",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Vinhedo",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": 2020,
        "opening_year": 2020,
        "operational_year": 2020,
        "construction_end_year": 2020,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": 25000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/blog/news-ascenty/ascenty-inicia-a-operacao-do-seu-segundo-data-center-no-seu-mega-campus-em-vinhedo/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_009",
        "facility_name": "Ascenty São Paulo 3",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Osasco",
        "address": null,
        "latitude": -23.492259,
        "longitude": -46.777232,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2020,
        "operational_year": 2020,
        "construction_end_year": null,
        "capacity_mw": 4.0,
        "it_load_mw": null,
        "facility_area_m2": 4000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/",
        "coordinate_status": "Validada",
        "data_quality": "Média"
    },
    {
        "facility_id": "DC_010",
        "facility_name": "Equinix SP5x",
        "operator": "Equinix",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Santana de Parnaíba",
        "address": "Av. Marcos Penteado de Ulhoa Rodrigues, 888",
        "latitude": null,
        "longitude": null,
        "facility_type": "Hyperscale",
        "status": "Operational",
        "construction_start_year": 2020,
        "opening_year": 2021,
        "operational_year": 2021,
        "construction_end_year": 2021,
        "capacity_mw": 14.4,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://www.equinix.com/br/pt/data-centers/americas-colocation/brazil-colocation/sao-paulo-data-centers/sp5x",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_011",
        "facility_name": "Ascenty Hortolândia 4",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Hortolândia",
        "address": null,
        "latitude": -22.896309,
        "longitude": -47.178493,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2021,
        "operational_year": 2021,
        "construction_end_year": null,
        "capacity_mw": 3.0,
        "it_load_mw": null,
        "facility_area_m2": 2000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/blog/artigos/data-center-em-sao-paulo/",
        "coordinate_status": "Validada",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_012",
        "facility_name": "Ascenty Hortolândia 5",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Hortolândia",
        "address": null,
        "latitude": -22.896309,
        "longitude": -47.178493,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": 2021,
        "opening_year": 2022,
        "operational_year": 2022,
        "construction_end_year": 2022,
        "capacity_mw": 30.0,
        "it_load_mw": null,
        "facility_area_m2": 23000.0,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/blog/artigos/data-center-em-sao-paulo/",
        "coordinate_status": "Validada",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_013",
        "facility_name": "Ascenty São Paulo 4",
        "operator": "Ascenty",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Osasco",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "Colocation",
        "status": "Operational",
        "construction_start_year": 2022,
        "opening_year": 2023,
        "operational_year": 2023,
        "construction_end_year": 2023,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://ascenty.com/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_014",
        "facility_name": "Scala Campus Tamboré",
        "operator": "Scala Data Centers",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "SP",
        "city": "Barueri",
        "address": null,
        "latitude": -23.498104,
        "longitude": -46.81614,
        "facility_type": "Hyperscale",
        "status": "Operational / Expansion",
        "construction_start_year": 2022,
        "opening_year": null,
        "operational_year": null,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://scaladatacenters.com/",
        "coordinate_status": "Validada",
        "data_quality": "Média"
    },
    {
        "facility_id": "DC_015",
        "facility_name": "Scala SGIGSM01",
        "operator": "Scala Data Centers",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "RJ",
        "city": "São João de Meriti",
        "address": null,
        "latitude": -22.799883,
        "longitude": -43.353842,
        "facility_type": "Edge / Colocation",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2023,
        "operational_year": 2023,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://scaladatacenters.com/",
        "coordinate_status": "Validada",
        "data_quality": "Média"
    },
    {
        "facility_id": "DC_016",
        "facility_name": "Scala SPOAPA01",
        "operator": "Scala Data Centers",
        "country": "Brazil",
        "region": "Sul",
        "state_region": "RS",
        "city": "Porto Alegre",
        "address": null,
        "latitude": -30.002768,
        "longitude": -51.198149,
        "facility_type": "Edge",
        "status": "Operational",
        "construction_start_year": null,
        "opening_year": 2023,
        "operational_year": 2023,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://scaladatacenters.com/",
        "coordinate_status": "Validada",
        "data_quality": "Média"
    },
    {
        "facility_id": "DC_017",
        "facility_name": "Equinix RJ3",
        "operator": "Equinix",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "RJ",
        "city": "São João de Meriti",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "Colocation / Hyperscale",
        "status": "Recent / Expansion",
        "construction_start_year": 2024,
        "opening_year": null,
        "operational_year": null,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://www.equinix.com/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_018",
        "facility_name": "RT-One Uberlândia",
        "operator": "RT-One",
        "country": "Brazil",
        "region": "Sudeste",
        "state_region": "MG",
        "city": "Uberlândia",
        "address": "Região da MGC-497",
        "latitude": null,
        "longitude": null,
        "facility_type": "AI Hyperscale",
        "status": "Project / Implementation",
        "construction_start_year": null,
        "opening_year": null,
        "operational_year": null,
        "construction_end_year": null,
        "capacity_mw": 400.0,
        "it_load_mw": null,
        "facility_area_m2": 1000000.0,
        "building_area_m2": 245000.0,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": "Liquid Cooling",
        "source_url": "https://www.uberlandia.mg.gov.br/2026/02/23/projeto-do-primeiro-data-center-de-ia-da-regiao-sudeste-do-pais-avanca-em-uberlandia/",
        "coordinate_status": "A validar",
        "data_quality": "Alta"
    },
    {
        "facility_id": "DC_019",
        "facility_name": "Data Center ByteDance / Pecém",
        "operator": "OMNIA / Pátria",
        "country": "Brazil",
        "region": "Nordeste",
        "state_region": "CE",
        "city": "São Gonçalo do Amarante",
        "address": "Complexo Industrial e Portuário do Pecém",
        "latitude": null,
        "longitude": null,
        "facility_type": "AI Hyperscale",
        "status": "Under Construction",
        "construction_start_year": 2026,
        "opening_year": null,
        "operational_year": null,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": 200.0,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://www.datacentermap.com/brazil/fortaleza/",
        "coordinate_status": "A validar",
        "data_quality": "Média"
    },
    {
        "facility_id": "DC_020",
        "facility_name": "Scala AI City",
        "operator": "Scala Data Centers",
        "country": "Brazil",
        "region": "Sul",
        "state_region": "RS",
        "city": "Eldorado do Sul",
        "address": null,
        "latitude": null,
        "longitude": null,
        "facility_type": "AI Hyperscale",
        "status": "Project",
        "construction_start_year": null,
        "opening_year": null,
        "operational_year": null,
        "construction_end_year": null,
        "capacity_mw": null,
        "it_load_mw": null,
        "facility_area_m2": null,
        "building_area_m2": null,
        "number_of_buildings": null,
        "number_of_data_halls": null,
        "water_usage_m3_year": null,
        "wue": null,
        "pue": null,
        "cooling_type": null,
        "source_url": "https://www.eldorado.rs.gov.br/",
        "coordinate_status": "A validar",
        "data_quality": "Média"
    }
]

CLASSES_MAPBIOMAS = {
    "Vegetação": [3,4,5,6,9,10,11,12],
    "Construído": [24,25],
    "Água": [26,33],
}

def catalogo_dataframe():
    import pandas as pd
    df = pd.DataFrame(DATA_CENTERS)
    df["coordinates_valid"] = df["latitude"].notna() & df["longitude"].notna()
    return df
